### ISSUE TITLE
Evaluate how A&A and the table access works on Daiquiri

### ISSUE THREAD

**Issue by gschwend** [linea-it/lsp_daiquiri#29]

**Comment by glaubervila** [comment]
@deborajanini , @gschwend Fui adicionado a esta issue mas ela não tem descrição e não faço ideia do que seja, nunca ouvi a expressão A&A acredito que não seja uma tarefa minha. 
Se for é necessário que alguem a descreva.

**Comment by gschwend** [comment]
Apenas para registro, seria a avaliação de como as permissões das tabelas seriam gerenciadas de acordo com os perfis de usuários para que todos tenham visibilidade das tablelas públicas e apenas os membros das colaborações possam ver as tabelas privadas do seu respectivo projeto. 

O @glaubervila já demostrou que o daiquiri possui ferramenta de controde de permissões com a possibilidade de definição de permissões individuais e por grupo. 

Considero a tarefa concluída.
