### ISSUE TITLE
Evaluate and compare LIneA@TAP Service vs Others

### ISSUE THREAD

**Issue by gschwend** [linea-it/lsp_daiquiri#30]
O objetivo é testar os limites da ferramenta e identificar os principais requisitos necessários para o ambiente de produção.

- [x]  testar as consultas que serão usadas no curso
- [x]  testar o serviço com o uso de consultas 'pesadas'
- [x]  verificar o tempo de execução limite de uma consulta
- [x]  testar o serviço tap com o Topcat e o Astroquery
- [x]  testar o serviço tap com a biblioteca Astroquery via Jupyter Notebook
- [x]  documentar os tipos de consultas científicas e o seus resultados (volume, time, número de linhas etc)

Executar testes similares aos realizados no ambiente do LIneA nos seguintes sites:

OBS: não será possível fazer testes idênticos devido a não conformidade dos catálogos, a ideia é validar que consultas similares podem ser executadas tanto no LIneA quanto nesses locais. Se algum dos sites abaixo não tiver serviço TAP então basta sinalizar como não disponível no documento de resultados.

- [x] Casjobs no LIneA
- [x] Casjobs em JHU
- [x] Noirlab
- [x] CADC
- [x] SIMBAD
- [x] CDS Vizier
- [x] Documentar e apresentar comparação nas reuniões de checkpoint do projeto LSP

**Comment by adrianopieres** [comment]
Inseri os testes (nem todos os testes foram executados) neste documento do google docs:
[https://docs.google.com/document/d/10ab6b5ogF60wPOAU-75UdUc1H973hNXtZhHUtHcH3EY/edit?usp=sharing](https://docs.google.com/document/d/10ab6b5ogF60wPOAU-75UdUc1H973hNXtZhHUtHcH3EY/edit?usp=sharing)

**Comment by gschwend** [comment]
FYI ainda em fase de revisão, agora incluindo @ndmallmann para ajudar na validação.
