### ISSUE TITLE
Especificar uma página de Home para o User Query/Daiquiri

### ISSUE THREAD

**Issue by glaubervila** [linea-it/lsp_daiquiri#34]
O Daiquiri tem uma página Home, a principio pensei que seria possivel removela completamente deixando apenas a página query. mas a página Home do daiquiri é uma dependencia vamos precisar definir um conteudo/layout para está página. 

edição 25/04/24: 
apenas trocar o header para ficar com a mesma aparência do science server (cinza, com logo, etc) 
foi para o issue #22

**Comment by glaubervila** [comment]
@gschwend Criei essa issue por favor confere a configuração dos projetos

**Comment by gschwend** [comment]
@glaubervila por enquanto vai fazendo com o layout default, vamos pensar num layout com a nossa identidade visual. @luiz-nicolaci

**Comment by gschwend** [comment]
https://docs.google.com/presentation/d/1PXWS60GTkgwpJXGnKL1zei_yUgakrDe5AnHQndrgv4g/edit#slide=id.g1f8026fe9f9_0_44
