### ISSUE TITLE
download traz arquivo vazio

### ISSUE THREAD

**Issue by gschwend** [linea-it/lsp_daiquiri#58]
download da tabela criada em formato CSV traz apenas o header

**Comment by glaubervila** [comment]
Mesmo após a recriação do ambiente -dev o problema persist  é necessári investigar.

**Comment by glaubervila** [comment]
Investigando o problema me deparei com um erro de versão do pg_dump. 

```bash
pg_dump: error: server version: 14.10; pg_dump version: 13.15 (Debian 13.15-0+deb11u1)
pg_dump: error: aborting because of server version mismatch
```

O erro apareceu após tentar reproduzir o comando que aparece no log: 

```bash
daiquiri@3436beb5aa98:/app$ pg_dump --no-owner --data-only --inserts --dbname=postgresql://user_dridev:278e41447c72@desdb4.linea.org.br:5432/prod_gavo --table="mydb_glauber_costa"."2024-07-25-21-20-02-272388"
```

**Comment by glaubervila** [comment]
Foi necessário: 
- Alterar a imagem base subindo a versão do debian do bulleye para bookworm e python da 3.9 para 3.11. 
- Atualizar o postgresql-client-13 para postgresql-client-15
