### ISSUE TITLE
Página de overview do survey 2MASS

### ISSUE THREAD

**Issue by gschwend** [linea-it/lsp_daiquiri#90]

**Comment by adrianopieres** [comment]
Eu basicamente fiz a tradução do abstract do paper. Segue abaixo:

2MASS
Paper link: https://iopscience.iop.org/article/10.1086/498708/pdf
Between 1997 June and 2001 February the Two Micron All Sky Survey (2MASS) collected 25.4 Tbytes of raw imaging data covering 99.998% of the celestial sphere in the near-infrared J (1.25 μm), H (1.65 μm), and Ks (2.16 μm) bandpasses. Observations were conducted from two dedicated 1.3 m diameter telescopes located at Mount Hopkins, Arizona, and Cerro Tololo, Chile. The 7.8 s of integration time accumulated for each point on the sky and strict quality control yielded a 10 σ point-source detection level of better than 15.8, 15.1, and 14.3 mag at the J, H, and Ks bands, respectively, for virtually the entire sky. Bright source extractions have 1 σ photometric uncertainty of <0.03 mag and astrometric accuracy of order 100 mas. Calibration offsets between any two points in the sky are <0.02 mag. The 2MASS All-Sky Data Release includes 4.1 million compressed FITS images covering the entire sky, 471 million source extractions in a Point Source Catalog, and 1.6 million objects identified as extended in an Extended Source Catalog.

Entre junho de 1997 e fevereiro de 2001 o Two Micron All Sky Survey (2MASS) coletou 25,4 Tbytes de dados brutos de imagem cobrindo 99,998% da esfera celeste nas bands do infravermelho próximo J (1,25 μm), H (1,65 μm) e Ks (2,16 μm). As observações foram conduzidas a partir de dois telescópios dedicados de 1,3 m de diâmetro localizados em Mount Hopkins, Arizona, e Cerro Tololo, Chile. Os 7,8 s de tempo de integração acumulados para cada ponto no céu e o rigoroso controle de qualidade produziram um nível de detecção de fonte pontual de 10 σ melhor que 15,8, 15,1 e 14,3 mag nas bandas J, H e Ks, respectivamente, para quase todo o céu. Extrações de fontes brilhantes têm incerteza fotométrica de 1 σ <0,03 mag e precisão astrométrica da ordem de 100 mas. Os desvios de calibração entre quaisquer dois pontos no céu são <0,02 mag. O 2MASS All-Sky Data Release inclui 4,1 milhões de imagens FITS compactadas cobrindo todo o céu, 471 milhões de fontes extraídas em um Catálogo de Fontes Pontuais e 1,6 milhão de objetos identificados como extendidas em um Catálogo de Fontes Extendidas.
